### ISSUE TITLE
Links do not work

### ISSUE THREAD

**Issue by stefanreichhart** [webplatformz/practically-oriented-javascript-patterns#5]
practically-oriented-javascript-patterns/slides/05_Reactive.html#/2/3 (setters, live demo)
https://stackblitz.com/edit/js-zmimtd?embed=1&file=index.js&hideExplorer=1&hideNavigation=1 => Yikes! The page you requested couldn't be found.

practically-oriented-javascript-patterns/slides/05_Reactive.html#/2/7 (what is this pattern, live demo)
https://stackblitz.com/edit/js-vtbmnr?embed=1&file=index.js&hideExplorer=1&hideNavigation=1 => Yikes! The page you requested couldn't be found.

**Comment by r3dDoX** [comment]
done, renaming stackblitz projects breaks the link...
